INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (nextval('SEQ_ROL'), 'ADMIN');
INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (nextval('SEQ_ROL'), 'EMPLOYEE');
INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (nextval('SEQ_ROL'), 'USER');

-- admin@admin / admin
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (nextval('SEQ_USR'), 'admin@admin', '$2a$10$Tbt2mTwOerxIn396uy0x4eOKz3vXYqYQ.5Ntd7E5bkrklT7NIAiqi', 'Admin', 'Admin', 'Adminowo', '997998999', TRUE);
-- emp@emp / pass
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (nextval('SEQ_USR'), 'emp@emp', '$2a$10$9EEK56M/YFFzWPMO35SyOusOTo.ldntvn1wKq5IvYZWaotBozbkXK', 'Emp', 'Emp', 'Empowo', '123456789', TRUE);
-- usr@usr / pass
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (nextval('SEQ_USR'), 'usr@usr', '$2a$10$9EEK56M/YFFzWPMO35SyOusOTo.ldntvn1wKq5IvYZWaotBozbkXK', 'User', 'User', 'Userowo', '987654321', TRUE);
-- john@doe / pass
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_FIRST_NAME, USR_LAST_NAME, USR_CITY, USR_PHONE, USR_ACTIVE) VALUES (nextval('SEQ_USR'), 'john@doe', '$2a$10$9EEK56M/YFFzWPMO35SyOusOTo.ldntvn1wKq5IvYZWaotBozbkXK', 'John', 'Doe', 'New York', '666555666', FALSE);

INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'ADMIN'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'EMPLOYEE'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'emp@emp'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'EMPLOYEE'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'emp@emp'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'usr@usr'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'john@doe'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));

INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'Audi', 'A4', 'Black', 'E1 XDDD');
INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'Alfa Romeo', 'Giulia Coupe', 'Red', 'WA ALFA');
INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'Kia', 'Stinger', 'Silver', 'EBR KIA');
INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'Ferrari', 'LaFerrari', 'Red', 'EL LAXD');
INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'McLaren', 'P1', 'Silver', 'E0 P1');
INSERT INTO CARS (CAR_ID, CAR_MAKE, CAR_MODEL, CAR_COLOUR, CAR_PLATE)	VALUES (nextval('SEQ_CAR'), 'Audi', 'A5', 'Blue', 'EBR 69XD');

INSERT INTO RESERVATIONS (RSV_ID, RSV_USR_ID, RSV_CAR_ID, RSV_DATE_START, RSV_DATE_END, RSV_STATUS) VALUES (nextval('SEQ_RSV'), (SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT CAR_ID FROM CARS WHERE CAR_PLATE = 'E1 XDDD'), CURRENT_DATE, null, 'ACTIVE');
INSERT INTO RESERVATIONS (RSV_ID, RSV_USR_ID, RSV_CAR_ID, RSV_DATE_START, RSV_DATE_END, RSV_STATUS) VALUES (nextval('SEQ_RSV'), (SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'emp@emp'), (SELECT CAR_ID FROM CARS WHERE CAR_PLATE = 'WA ALFA'), CURRENT_DATE, null, 'WAITING');
INSERT INTO RESERVATIONS (RSV_ID, RSV_USR_ID, RSV_CAR_ID, RSV_DATE_START, RSV_DATE_END, RSV_STATUS) VALUES (nextval('SEQ_RSV'), (SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'usr@usr'), (SELECT CAR_ID FROM CARS WHERE CAR_PLATE = 'EBR KIA'), '2018-05-06', '2018-05-22', 'FINISHED');
INSERT INTO RESERVATIONS (RSV_ID, RSV_USR_ID, RSV_CAR_ID, RSV_DATE_START, RSV_DATE_END, RSV_STATUS) VALUES (nextval('SEQ_RSV'), (SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'john@doe'), (SELECT CAR_ID FROM CARS WHERE CAR_PLATE = 'EL LAXD'), '2018-05-06', '2018-05-07', 'CANCELED');